version: "3.2"

services:
  mongodb:
    image: mongo:4.2.8
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "dummyPass"

  mongo_seed:
    build: ./mongo-seed
    links:
      - mongodb