version: "3.2"

services:
  mongodb:
    image: mongo:4.2.8
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "dummyPass"
    volumes:
      - ./dump:/dump
    networks:
      back:
        aliases:
          - "mongo.service.com.br"

  api:
    build: ./api
    environment:
      SERVER_PORT: "3001"
      GRPC_SERVER_HOST: "discount.calculator.service.com.br"
      GRPC_SERVER_PORT: "3002"
      DB_USER: "root"
      DB_PASS: "dummyPass"
      DB_HOST: "mongo.service.com.br"
      DB_DATABASE: "challenge"
      DB_PORT: "27017"
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
      - discount-calculator
    restart: always
    networks:
      back:

  discount-calculator:
    build: ./discount-calculator
    ports:
      - "3002:3002"
    depends_on:
      - mongodb
    restart: always
    networks:
      back:
        aliases:
          - "discount.calculator.service.com.br"

networks:
  back: